spring:
  application:
    name: consumer
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://eureka02.com:8762/eureka/,http://eureka01.com:8761/eureka/
#针对provider该服务做负载均衡
provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
