server:
  port: 8084
spring:
  application:
    name: eureka-zuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka02.com:8762/eureka/,http://eureka01.com:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    routes:
      enabled: true